[[redirects]]
  from = "/user/*"
  to = "http://54.180.152.95:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/publish/*"
  to = "http://13.125.56.155:5001/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/prototype/*"
  to = "http://13.209.7.194:8000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200