[[redirects]]
  from = "/user/*"
  to = "http://13.125.250.138:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/publish/*"
  to = "http://54.66.54.30/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/prototype/*"
  to = "http://15.164.129.149:8000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200